
//  CUSTOMERS
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const OPEN_CUSTOMER_MODAL_NEW = 'OPEN_CUSTOMER_MODAL_NEW';
export const CLOSE_CUSTOMER_MODAL_NEW = 'CLOSE_CUSTOMER_MODAL_NEW';

export const OPEN_CUSTOMER_MODAL_EDIT = 'OPEN_CUSTOMER_MODAL_EDIT';
export const CLOSE_CUSTOMER_MODAL_EDIT = 'CLOSE_CUSTOMER_MODAL_EDIT';

export const OPEN_CUSTOMER_MODAL_DELETE = 'OPEN_CUSTOMER_MODAL_DELETE';
export const CLOSE_CUSTOMER_MODAL_DELETE = 'CLOSE_CUSTOMER_MODAL_DELETE';

export const SET_CREATE_CUSTOMER_DATA = 'SET_CREATE_CUSTOMER_DATA';
export const CLEAR_CREATE_CUSTOMER_DATA = 'CLEAR_CREATE_CUSTOMER_DATA';

export const SET_EDIT_CUSTOMER_DATA = 'SET_EDIT_CUSTOMER_DATA';
export const CLEAR_EDIT_CUSTOMER_DATA = 'CLEAR_EDIT_CUSTOMER_DATA';

export const SET_DELETE_CUSTOMER_DATA = 'SET_DELETE_CUSTOMER_DATA';
export const CLEAR_DELETE_CUSTOMER_DATA = 'CLEAR_DELETE_CUSTOMER_DATA';

//  PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const OPEN_PRODUCT_MODAL_NEW = 'OPEN_PRODUCT_MODAL_NEW';
export const CLOSE_PRODUCT_MODAL_NEW = 'CLOSE_PRODUCT_MODAL_NEW';

export const OPEN_PRODUCT_MODAL_EDIT = 'OPEN_PRODUCT_MODAL_EDIT';
export const CLOSE_PRODUCT_MODAL_EDIT = 'CLOSE_PRODUCT_MODAL_EDIT';

export const OPEN_PRODUCT_MODAL_DELETE = 'OPEN_PRODUCT_MODAL_DELETE';
export const CLOSE_PRODUCT_MODAL_DELETE = 'CLOSE_PRODUCT_MODAL_DELETE';

export const SET_CREATE_PRODUCT_DATA = 'SET_CREATE_PRODUCT_DATA';
export const CLEAR_CREATE_PRODUCT_DATA = 'CLEAR_CREATE_PRODUCT_DATA';

export const SET_EDIT_PRODUCT_DATA = 'SET_EDIT_PRODUCT_DATA';
export const CLEAR_EDIT_PRODUCT_DATA = 'CLEAR_EDIT_PRODUCT_DATA';

export const SET_DELETE_PRODUCT_DATA = 'SET_DELETE_PRODUCT_DATA';
export const CLEAR_DELETE_PRODUCT_DATA = 'CLEAR_DELETE_PRODUCT_DATA';

//  INVOICES
export const GET_INVOICES = 'GET_INVOICES';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const OPEN_INVOICE_MODAL_DELETE = 'OPEN_INVOICE_MODAL_DELETE';
export const CLOSE_INVOICE_MODAL_DELETE = 'CLOSE_INVOICE_MODAL_DELETE';

export const SET_INVOICE_DATA = 'SET_CREATE_INVOICE_DATA';
export const CLEAR_INVOICE_DATA = 'CLEAR_CREATE_INVOICE_DATA';

export const SET_INVOICE_ITEMS_LIST = 'SET_INVOICE_ITEMS_LIST';
export const CLEAR_INVOICE_ITEMS_LIST = 'CLEAR_INVOICE_ITEMS_LIST';

export const SET_INVOICE_ITEM_DATA = 'SET_INVOICE_ITEM_DATA';
export const CLEAR_INVOICE_ITEM_DATA = 'CLEAR_INVOICE_ITEM_DATA';

export const SET_INVOICE_ITEMS_TO_DELETE = 'SET_INVOICE_ITEMS_TO_DELETE';
export const CLEAR_INVOICE_ITEMS_TO_DELETE = 'CLEAR_INVOICE_ITEMS_TO_DELETE';
